# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testing.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'testing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtesting.proto\".\n\x0cRangeRequest\x12\x0f\n\x07idStart\x18\x01 \x01(\x05\x12\r\n\x05idEnd\x18\x02 \x01(\x05\" \n\x0eSingleResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\")\n\x0b\x44\x61taRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\"\x1b\n\x19InsertDataAcknowledgement2\x94\x01\n\x06\x44\x42Node\x12)\n\x05\x43ount\x12\r.RangeRequest\x1a\x0f.SingleResponse\"\x00\x12\'\n\x03Sum\x12\r.RangeRequest\x1a\x0f.SingleResponse\"\x00\x12\x36\n\x06Insert\x12\x0c.DataRequest\x1a\x1a.InsertDataAcknowledgement\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANGEREQUEST']._serialized_start=17
  _globals['_RANGEREQUEST']._serialized_end=63
  _globals['_SINGLERESPONSE']._serialized_start=65
  _globals['_SINGLERESPONSE']._serialized_end=97
  _globals['_DATAREQUEST']._serialized_start=99
  _globals['_DATAREQUEST']._serialized_end=140
  _globals['_INSERTDATAACKNOWLEDGEMENT']._serialized_start=142
  _globals['_INSERTDATAACKNOWLEDGEMENT']._serialized_end=169
  _globals['_DBNODE']._serialized_start=172
  _globals['_DBNODE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
